# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VisionGui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VisionGui(object):
    def setupUi(self, VisionGui):
        VisionGui.setObjectName("VisionGui")
        VisionGui.resize(1021, 551)
        self.centralwidget = QtWidgets.QWidget(VisionGui)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1021, 581))
        self.label.setMinimumSize(QtCore.QSize(1021, 551))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:\Vision\Media\Background.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(0, 410, 201, 151))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Unicode")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pushButton.setStyleSheet("QPushButton {\n"
"  border-color: white;\n"
"  color:white;\n"
"  border-width: 3px;        \n"
"  border-style: solid;\n"
"  border-radius: 40px;\n"
"  margin:30px;\n"
"  padding:30px;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(820, 410, 201, 151))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Unicode")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"  border-color: white;\n"
"  color:white;\n"
"  border-width: 3px;        \n"
"  border-style: solid;\n"
"  border-radius: 40px;\n"
"  margin:30px;\n"
"  padding:30px;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(380, -40, 321, 241))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("D:/Downloads/image0 (3).png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
      
        VisionGui.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(VisionGui)
        self.statusbar.setObjectName("statusbar")
        VisionGui.setStatusBar(self.statusbar)

        self.retranslateUi(VisionGui)
        QtCore.QMetaObject.connectSlotsByName(VisionGui)

    def retranslateUi(self, VisionGui):
        _translate = QtCore.QCoreApplication.translate
        VisionGui.setWindowTitle(_translate("VisionGui", "Vision"))
        self.pushButton.setText(_translate("VisionGui", "START"))
        self.pushButton_2.setText(_translate("VisionGui", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VisionGui = QtWidgets.QMainWindow()
    ui = Ui_VisionGui()
    ui.setupUi(VisionGui)
    VisionGui.show()
    sys.exit(app.exec_())
